#!/usr/bin/env python3
"""PostToolUse hook: flag comment blocks long enough to need justifying.

Default threshold is 8 lines — roughly p80 of a real codebase's comment blocks, so it fires on
outliers by distribution rather than by taste. Set COMMENT_CRITIC_THRESHOLD to retune it against
your own. Where a ruling belongs, and the skill that files it, are discovered from the repo;
COMMENT_CRITIC_HOME and COMMENT_CRITIC_SKILL override that.
Advisory: the edit already happened. It asks the three questions; it cannot answer them.
"""
import json
import os
import pathlib
import re
import subprocess
import tempfile
import sys

_raw = os.environ.get("COMMENT_CRITIC_THRESHOLD", "")
THRESHOLD = int(_raw) if _raw.isdigit() else 8
#: Code you did not write and will not edit: dependency trees, checked-in vendor directories and
#: build output, per ecosystem. Their comments are not yours to police, and one `go mod vendor`
#: or pod install would otherwise bury a real finding under thousands of them.
#:
#: Deliberately absent, because each is somebody's real source: `bin`, `env`, `external`,
#: `packages` (a pnpm or lerna monorepo keeps its own code there), `lib`, `src`, `out`.
VENDORED = {
    # cross-ecosystem
    "vendor", "third_party", "thirdparty", "vendored", ".cache",
    # javascript / typescript
    "node_modules", "bower_components", "jspm_packages", ".yarn", ".pnp", ".next", ".nuxt",
    ".svelte-kit", ".parcel-cache", ".turbo", ".angular",
    # python
    ".venv", "venv", "site-packages", "__pycache__", ".tox", ".nox", ".eggs", ".mypy_cache",
    ".pytest_cache", ".ruff_cache",
    # go
    "Godeps",
    # ruby / php
    "bundle", ".bundle",
    # jvm
    "build", "target", ".gradle", ".m2", "gradle",
    # .net
    "obj",
    # swift / apple
    "Pods", "Carthage", ".build", "DerivedData", ".swiftpm",
    # rust shares `target`; elixir, dart, haskell, terraform, cmake
    "deps", "_build", ".dart_tool", ".pub-cache", ".stack-work", "dist-newstyle", ".terraform",
    "cmake-build-debug", "cmake-build-release", "_deps",
    # generic output
    "dist", "coverage",
}


def vendored(path):
    """True when the path lives in a dependency or build tree.

    `COMMENT_CRITIC_SKIP` adds names; a name prefixed with `-` removes one, because a default
    like `build` or `dist` is somebody's real source directory, and a silent false negative
    cannot be noticed the way a false positive can.
    """
    skip, keep = set(VENDORED), set()
    for name in os.environ.get("COMMENT_CRITIC_SKIP", "").split(","):
        name = name.strip()
        if name.startswith("-"):
            keep.add(name[1:])
        elif name:
            skip.add(name)
    return any(p in skip and p not in keep for p in pathlib.PurePath(path).parts)


#: The banners generators actually emit. Every pattern names the file or the generator — a bare
#: "auto-generated" is ordinary prose ("tokens are auto-generated per session") and skipping on it
#: silently disarms the hook for a real file, which is the one failure nobody notices.
GENERATED = re.compile(
    r"@generated\b"
    r"|<auto-?generated"
    r"|\bcode generated by\b"
    r"|\bautogenerated by\b"
    r"|generated by the protocol buffer compiler"
    r"|\bgenerated code\b[^\n]{0,30}\bdo not (edit|modify)"
    r"|\bthis file (is|was|has been) (auto-?|automatically )?generated"
    r"|\bgenerated by\b[^\n]{0,60}\bdo not edit\b",
    re.I)


def generated(path, cwd, text=None):
    """True when the file's head declares it generated — its comments belong to the generator.

    Read from disk rather than from the edit, because a `.pb.go` is skipped on the strength of a
    header the edit itself never touches, and the diff path never carries one.
    """
    if text is None:
        try:
            text = (pathlib.Path(cwd) / path).read_text(errors="replace")
        except OSError:
            return False
    return bool(GENERATED.search("\n".join(text.split("\n")[:40])))


#: Conventional homes for a ruling, and the skills that file one. Looked up only to name them in
#: the message, so a wrong guess costs a misleading sentence, never a wrong write.
HOMES = ("docs/backlog", "docs/decisions", "docs/adr", "docs/rulings", "doc/adr", "adr", "docs")
SKILLS = ("backlog", "decisions", "adr")


def destination(cwd):
    """Where a relocated ruling goes and which skill files it, discovered when unconfigured.

    Zero config is the point: a repo that keeps decisions in `docs/adr/` should get told so
    without anyone setting an env var first. The env still wins, for a repo whose answer is
    two places or an unconventional name.
    """
    home = os.environ.get("COMMENT_CRITIC_HOME", "")
    skill = os.environ.get("COMMENT_CRITIC_SKILL", "")
    root = pathlib.Path(cwd)
    if not home:
        home = next((f"{n}/" for n in HOMES if (root / n).is_dir()), "a doc")
    if not skill:
        for base in (root / ".claude" / "skills", pathlib.Path.home() / ".claude" / "skills"):
            skill = next((n for n in SKILLS if (base / n).is_dir()), "")
            if skill:
                break
    return home, skill
#: Line-comment markers per language, never pooled: `#` opens a comment in Python and a
#: preprocessor directive in C. Source extensions only, and a language is listed only once —
#: a markdown heredoc is nearly all `#` headings and would fire on every document written,
#: which is how a hook gets switched off.
_SLASH = ("//",)
LINE = dict.fromkeys(
    (".swift", ".js", ".mjs", ".cjs", ".ts", ".tsx", ".jsx", ".java", ".kt", ".kts", ".c", ".h",
     ".cpp", ".hpp", ".cc", ".m", ".mm", ".go", ".rs", ".cs", ".scala", ".dart", ".php", ".zig",
     ".groovy", ".proto", ".gradle"), _SLASH)
LINE.update(dict.fromkeys(
    (".py", ".rb", ".sh", ".bash", ".zsh", ".fish", ".pl", ".pm", ".r", ".jl", ".nim", ".cr",
     ".ex", ".exs", ".tf", ".yaml", ".yml", ".toml"), ("#",)))
LINE.update(dict.fromkeys((".sql", ".hs", ".lua", ".elm", ".adb", ".ads"), ("--",)))
LINE.update(dict.fromkeys((".lisp", ".clj", ".cljs", ".el", ".scm", ".asm"), (";",)))
LINE.update(dict.fromkeys((".tex", ".erl", ".hrl"), ("%",)))
LINE[".f90"] = ("!",)

#: Block comments as (open, close), counted only when the opener starts the line — so a long SQL
#: string assigned in Python, or a `/*` trailing real code, is not read as prose.
_C_BLOCK = (("/*", "*/"),)
BLOCK = dict.fromkeys([e for e, m in LINE.items() if m is _SLASH], _C_BLOCK)
BLOCK[".py"] = (('"""', '"""'), ("\'\'\'", "\'\'\'"))
BLOCK[".lua"] = (("--[[", "]]"),)
BLOCK[".hs"] = (("{-", "-}"),)

SOURCE = tuple(LINE)


def markers(path):
    ext = pathlib.PurePath(path).suffix.lower()
    return LINE.get(ext, ()), BLOCK.get(ext, ())


def runs(text, path):
    """Yield (start_line, length) for each comment block longer than THRESHOLD."""
    line_marks, blocks = markers(path)
    start = length = 0
    closing = None
    for n, raw in enumerate(text.split("\n"), 1):
        line = raw.strip()
        if closing:
            comment = True
            if closing in line:
                closing = None
        else:
            opener = next(((o, c) for o, c in blocks if line.startswith(o)), None)
            comment = bool(opener) or any(line.startswith(m) for m in line_marks)
            if opener and opener[1] not in line[len(opener[0]):]:
                closing = opener[1]
        if comment:
            if not length:
                start = n
            length += 1
        else:
            if length > THRESHOLD:
                yield start, length
            length = 0
    if length > THRESHOLD:
        yield start, length
_HUNK = re.compile(r"^@@ -\d+(?:,\d+)? \+(\d+)")


def bash_added(cwd):
    """Yield (path, start_line, length) for long comment blocks this command added.

    Bash writes a file a hundred ways — a heredoc, `sed -i`, a python one-liner, a generator
    script. Parsing the command to find them is unwinnable, so this asks git what landed instead.
    Unstaged only: the just-written change, not the whole branch's uncommitted work.
    """
    def git(*args):
        return subprocess.run(("git",) + args, cwd=cwd, capture_output=True, text=True, timeout=3)

    try:
        diff = git("diff", "-U0", "--no-color", "--no-ext-diff")
        new = git("ls-files", "--others", "--exclude-standard")
    except Exception:
        return
    if diff.returncode or new.returncode:
        return

    # A file git has never seen has no diff — every line of it is new.
    for name in new.stdout.split("\n"):
        if name.endswith(SOURCE) and not vendored(name):
            try:
                body = (pathlib.Path(cwd) / name).read_text(errors="replace")
            except OSError:
                continue
            if generated(name, cwd, body):
                continue
            for start, length in runs(body, name):
                yield name, start, length

    path, base, added = None, 0, []
    for line in diff.stdout.split("\n") + ["diff --git "]:
        if line.startswith(("diff --git ", "@@ ")):
            if path and added:
                for s, n in runs("\n".join(added), path):
                    yield path, base + s - 1, n
            added = []
            hunk = _HUNK.match(line)
            if hunk:
                base = int(hunk.group(1))
        elif line.startswith("+++ b/"):
            target = line[6:]
            path = target if (target.endswith(SOURCE) and not vendored(target)
                              and not generated(target, cwd)) else None
        elif line.startswith("+") and path:
            added.append(line[1:])


def written(tool, data):
    if tool == "Write":
        return data.get("content", "")
    if tool == "Edit":
        return data.get("new_string", "")
    if tool == "MultiEdit":
        return "\n\n".join(e.get("new_string", "") for e in data.get("edits", []))
    return ""


def unseen(hits, cwd):
    """Drop hits already reported. A block stays in the diff until fixed or committed, so
    without this every later Bash command repeats the same warning until it is noise."""
    cache = pathlib.Path(tempfile.gettempdir()) / "comment-critic-seen"
    try:
        old = set(cache.read_text().split("\n"))
    except OSError:
        old = set()
    fresh = [h for h in hits if f"{cwd}:{h[0]}:{h[2]}" not in old]
    if fresh:
        try:
            keys = list(old | {f"{cwd}:{h[0]}:{h[2]}" for h in fresh})
            cache.write_text("\n".join(keys[-500:]))
        except OSError:
            pass
    return fresh


def main():
    try:
        payload = json.load(sys.stdin)
    except Exception:
        return 0

    tool = payload.get("tool_name", "")
    if tool not in {"Write", "Edit", "MultiEdit", "Bash"}:
        return 0

    tool_input = payload.get("tool_input", {})
    cwd = payload.get("cwd") or os.getcwd()
    if tool == "Bash":
        hits = unseen(list(bash_added(cwd)), cwd)
    else:
        path = tool_input.get("file_path", "?")
        if not path.endswith(SOURCE) or vendored(path) or generated(path, cwd):
            return 0
        hits = [(path, s, n) for s, n in runs(written(tool, tool_input), path)]
    if not hits:
        return 0

    home, skill = destination(cwd)
    found = [(s, n) for _, s, n in hits]
    path = ", ".join(dict.fromkeys(h[0] for h in hits))
    where = ", ".join(f"~line {s} ({n} lines)" for s, n in found[:3])
    print(
        f"Comment block over {THRESHOLD} lines in {path}: {where}.\n"
        "Three questions: is it needed? will it change what someone does? "
        "can it be shorter?\n"
        "Comment why, not what. If the explanation is longer than the code, cut the explanation. "
        f"A ruling or a measurement belongs in {home} — link, don't restate."
        + (f" Record it with the `{skill}` skill; do not hand-roll the file." if skill else ""),
        file=sys.stderr,
    )
    return 2


if __name__ == "__main__":
    sys.exit(main())
